spring:
  application:
    name: inventory-service
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  datasource:
    url: jdbc:h2:mem:inventorydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  cloud:
    stream:
      function:
        definition: reserveInventory;releaseInventory;inventoryEvents
      bindings:
        reserveInventory-in-0:
          destination: order.commands
          group: inventory-service
        releaseInventory-in-0:
          destination: order.commands
          group: inventory-service
        inventoryEvents-out-0:
          destination: inventory.events
          content-type: application/json

server:
  port: 8083

